### ISSUE TITLE
Unable to build.

### ISSUE THREAD

**Issue by KottV** [mohragk/VermeerMonosynth-1#11]
Hi,

I'm trying to compile VermeerMonosynth-1 (Linux gcc8) and stuck with bunch of errors.
While I can "fix" some missing includes and replace isnan to std::isnan, most problem is conflict with ADSR class:

> In file included from ../../source/MonoSynth.h:31,
                 from ../../source/PluginProcessor.h:33,
                 from ../../source/OscillatorSection.h:18,
                 from ../../source/OscillatorSection.cpp:12:
../../source/adsr/ADSR.h:78:15: error: reference to ‘ADSR’ is ambiguous
 inline double ADSR::process() {
               ^~~~
In file included from ../../../../JUCE-5.4.3/modules/juce_audio_basics/juce_audio_basics.h:94,
                 from ../../source/../JuceLibraryCode/JuceHeader.h:17,
                 from ../../source/OscillatorSection.cpp:11:
../../../../JUCE-5.4.3/modules/juce_audio_basics/utilities/juce_ADSR.h:34:7: note: candidates are: ‘class juce::ADSR’
 class ADSR
       ^~~~
In file included from ../../source/MonoSynth.h:31,
                 from ../../source/PluginProcessor.h:33,
                 from ../../source/OscillatorSection.h:18,
                 from ../../source/OscillatorSection.cpp:12:
../../source/adsr/ADSR.h:23:7: note:                 ‘class ADSR’
 class ADSR {
       ^~~~
../../source/adsr/ADSR.h: In function ‘double process()’:
../../source/adsr/ADSR.h:79:13: error: ‘state’ was not declared in this scope
     switch (state) {

There are other errors, but I'd like to beat this one at first.

**Comment by mohragk** [comment]
Yes, this has to do with newer versions of Juce where an ADSR namespace/class is included as well. I suggest changing the classname to Envelope or something similar.

**Comment by mohragk** [comment]
Another solution is trying to build with an older version of JUCE: 5.4.1. You can find older versions here: https://github.com/juce-framework/JUCE/releases.

N.B. this project was made as a VST2 plugin, but VST2 is no longer available,  Steinberg pulled the license. You should port this project to VST3 as newer versions of Juce natively support that SDK.
